# Generated by Django 5.0.2 on 2024-02-21 11:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('fname', models.CharField(blank=True, max_length=50, null=True)),
                ('lname', models.CharField(blank=True, max_length=50, null=True)),
                ('family_role', models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('son', 'Son'), ('daughter', 'Daughter'), ('brother', 'brother'), ('sister', 'sister')], max_length=50, null=True)),
                ('profession', models.CharField(blank=True, max_length=50, null=True)),
                ('fravorite_food', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(blank=True, max_length=50, null=True)),
                ('lives_in', models.CharField(blank=True, max_length=50, null=True)),
                ('fravorite_holiday', models.CharField(blank=True, max_length=50, null=True)),
                ('greatest_fear', models.CharField(blank=True, max_length=50, null=True)),
                ('quote', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('fname', models.CharField(blank=True, max_length=50, null=True)),
                ('lname', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profile', models.ImageField(blank=True, default='user/dummy.png', null=True, upload_to='user/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
