# Generated by Django 5.0.2 on 2024-02-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApi', '0002_familymember_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='image',
            field=models.ImageField(blank=True, default='user/dummy.png', null=True, upload_to='family/'),
        ),
    ]
